export { author } from './helper/author.js'
export { config } from './helper/config'
export { features } from './helper/features'
export { pkg } from './helper/pkg'
export { prefixLines } from './helper/prefix-lines'
export { jsCodeToMd } from './helper/js-code-to-md.js'
export { stripJsdocComment } from './helper/strip-js-doc-comment'
export { getRepositoryUrl } from './helper/get-repository-url.js'
export { default as kebab } from 'lodash/kebabCase.js'
export { default as repeat } from 'lodash/repeat.js'
